name: python 3.9
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - pip
  - pip:
      - julia
      - pandas
      - scipy
      - scikit-learn
      - urllib3
      - beautifulsoup4
      - requests
